export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const UPDATE_PURCHASABLE = "UPDATE_PURCHASABLE";

export const RESET_INGREDIENT = "RESET_INGREDIENT";

export const LOAD_ORDERS = "LOAD_ORDERS";
export const LOAD_FAIL_ORDERS = "LOAD_FAIL_ORDERS";

export const AUTHT_SUCCESS="AUTHT_SUCCESS";
export const AUTHT_FAIL="AUTHT_FAIL";
export const AUTHT_LOADING="AUTHT_LOADING";

export const AUTHT_LOGOUT="AUTHT_LOGOUT";
